### ISSUE TITLE
Object>>#isLiteral is part of #GreaseVASTCoreApp

### ISSUE THREAD

**Issue by Noschvie** [PortingPDFtalk/VASTValues#2]
Hello Christian

loading VASTValues into VAST 2021 / 10.0.2 x64 leads to this:

Object>>#isLiteral seems to be part of the application named #GreaseVASTCoreApp too.

Have loaded "our application" and want to have a look to your "Values" application.

**Comment by ChristianHaider** [comment]
Hi Norbert (@Noschvie)

thanks for checking out the Values package in VAST.
The current fileout is not the finished version, but we are working on it and it should be ready in a few days.

Thank you for the hint about Grease! 
I will check if we should use Grease as a prerequisite. This might be justified, since I use Grease on Gemstone as well.
If so, I see if I can use it.

**Comment by ChristianHaider** [comment]
Thanks again!
We added #GreaseVASTCoreApp as prerequisite and removed most #isLiteral methods.
We found that #isLiteral is missing for Character - so we added only that.

**Comment by marianopeck** [comment]
If you agree, I can add this method to `GreaseVASTCoreApp` in the about to be released VAST 2022.
